### ISSUE TITLE
How might we add support for multiple languages?

### ISSUE THREAD

**Issue by pglevy** [Bixal/med-supply-cat#9]
The client mentioned they are interested in making this content available in multiple languages.

Development has indicated we already have the infrastructure for supporting "internationalization" (i18n).

How might we incorporate the ability to switch between languages?

**Comment by kbchumley** [comment]
**After doing some searching, here's the basic definitions and crossover:**

- Internationalization is the process of neutralizing the code, content, and design so that, down the road, it’ll be easier to adapt your product to additional cultures without having to completely re-engineer it.

- Localization is the adaptation of your software or mobile application product to meet the language, culture, and other requirements of each locale. 

**In addition to creating placeholder keys, internationalization involves some other best practices:**
-  Enabling cultural formatting, including number formats and systems, time zones, personal information, and text formatting
-  Organizing your source code
- Optimizing for your code language ([lokalise ](https://lokalise.com/blog/)supports all major code languages and frameworks, including Python, Vue, Java, and Rails)



**Questions to be asked & Things to consider:** 
- What languages does the software need adapted too? (english and spanish? or more languages?)
- are we going to do any Psuedo-Localization( process of “testing” the space that different languages will take up in your finished design, allowing you to understand the expansion, contraction, or vertical space needed — without actually having to conduct a translation.)
- Is the client willing to pay for a website translation platform or do they already have a provider?

### note:
- Drupal 8 has built-in multilingual capabilities
- Website Translation Addons & Plugins like google translate though they can be less accurate

**Comment by kbchumley** [comment]
**Language Selector Design Options**

**Dedicated mini header for langauges:** This option is good for a minimal layout with an audience that needs less language options
**Modal/Pop up built in Header:** This option forces the user to choose a language or exit the modal. This is a good option for scanning the page without added noise
**Button Drop Down built in header:** This option is simpler most obvious solution - debate between using the world English as an indicator or the word translate.

**Comment by pglevy** [comment]
Thanks Kayla! Leaning towards a link/button in the secondary links of the header, close to what you have for the third option, and going with translate for label. This works nicely with the [extended header](https://codepen.io/pglevy/pen/NWpPyMQ?editors=1000) (though not the basic header without some mods). We can also put it in the [footer](https://codepen.io/pglevy/pen/qBrEyOy?editors=1000), so we have some version of it in our templates by default. Can still play around with these, but I think this is a good start. We don't have to build the actual selector for now.

**Comment by pglevy** [comment]
closed by #16
